### ISSUE TITLE
Notes on Usage Examples / ESM loader / node v20 / non-bdd test reporter

### ISSUE THREAD

**Issue by NikitaIT** [vitalets/playwright-bdd#164]
## Disclaimer

I in no way claim that the examples I have given are correct and suitable for everyone. However, I often see how developers start projects with very old templates (for example, all the official nextjs examples at the beginning of the year were for node 10) and do not even suspect that modern LTS versions of nodejs support esm natively, and also contain modern testing tools.

## Faster modern ESM loader

https://github.com/vitalets/playwright-bdd/blob/79b598db3fb3f351d7530f2b4ea731cf9404a471/examples/esm/package.json#L4

Instead of `--loader=ts-node/esm`, we can use `--import tsx/esm --experimental-specifier-resolution=node`. Or both.

This flag is discouraged and may be removed in a future version of Node.js. Please use [--import with register()](https://nodejs.org/api/module.html#enabling) instead.

```ts
cross-env NODE_OPTIONS=\"--import tsx/esm  --import core-js/actual --experimental-specifier-resolution=node\" bddgen
```

## TS compiled to node v10

https://github.com/vitalets/playwright-bdd/blob/79b598db3fb3f351d7530f2b4ea731cf9404a471/examples/esm/tsconfig.json#L6

- 'node10' (previously called 'node') for Node.js versions older than v10, which only support CommonJS require. You probably won’t need to use node10 in modern code. [tsconfig/#moduleResolution](https://www.typescriptlang.org/tsconfig/#moduleResolution)

We can use `nodenext`, but this will cause problems with older libraries. So, it's better to use `bundler` as default, and probably use `import ... from "./file.ts"` file extensions.

## What if some of our tests are standard playwright tests without `playwright-bdd`?

We should probably launch another reporter or somehow handle this situation normally. Now if I add a test without bdd I get an error.
https://github.com/vitalets/playwright-bdd/blob/79b598db3fb3f351d7530f2b4ea731cf9404a471/src/reporter/cucumber/messagesBuilder/TestCaseRun.ts#L76

**Comment by vitalets** [comment]
Hi @NikitaIT ! Thanks for the input. I agree that examples should provide good defaults. To the points:

> Faster modern ESM loader

This is just a reference from official Cucumber docs for ESM: https://github.com/cucumber/cucumber-js/blob/main/docs/transpiling.md#loader-option
Hopefully, after https://github.com/vitalets/playwright-bdd/issues/136 we will remove this at all, because Playwright handles ESM internally.

> TS compiled to node v10

Fixed in dev, good catch!

> What if some of our tests are standard playwright tests without playwright-bdd?

Handling such mix of tests would be very difficult. Could you try to move non-bdd tests to a separate project within the same playwright.config.ts? It should work.
