### ISSUE TITLE
Question: Filter tests to be executed by Playwright using tags

### ISSUE THREAD

**Issue by tjaeuth** [vitalets/playwright-bdd#172]
Hi,

your project is amazing, well done. I had implemented my a translation from Gherkin to Playwright on my own but never published.
I would like to replace mine with yours.

However, I don't understand the selection of tests that must be executed by Playwright using tags.
In Playwright we use `--grep "@<your-tag>"`. So in a case like:
```
@my-custom-tag
Scenario: My scenario...
```

I would like to run just this scenario with `npx playwright test --grep "@my-custom-tag>`.
If I got it correctly, in your implementation we first need to generate the steps we later want to execute like this:
`npx bddgen --tags @my-custom-tag`

This will only generate those steps that are tagged with `my-custom-tag`.
Afterwards, we can execute the test by running `npx playwright test`.

I see two downsides of this approach.
1. You have to regenerate the steps everytime you change the tag in your test execution.
2. How do you combine Playwright tests generated by bddgen with usual tagged Playwright tests?

I would simply put the tags into the titles of the tests, so we can reuse the `--grep` functionality of Playwright.

Maybe I am missing something. Could you please clarify on this?

**Comment by vitalets** [comment]
Hi @tjaeuth ! 
Good point. I should improve docs on that. 
Since Playwright 1.42 cucumber tags are just simply mapped to Playwright tags (not in test title, but into `tag` option). It was intentional decision to not modify test titles by tooling.
In general you are right - there are 2 options to run scenario with **@some-tag**:

1. `npx bddgen --tags "@some-tag" && npx playwright test` - generate only that scenario and run with Playwright what we get in spec files
2. `npx bddgen && npx playwright test --grep "@some-tag"` - generate all scenarios, but filter with Playwright what to run

Which works better depends on dev workflow in the project.

**Comment by tjaeuth** [comment]
@vitalets,

Thanks for highlighting the two options. The second one is what I would like to use but it is not working in my case.

I am using playwright 1.44.1.

Do you have a reference where I can read about the tag option you are mentioning? 
I didn't know that Playwright is supporting a different tagging mechanism then those in the titles.

**Comment by vitalets** [comment]
>  but it is not working in my case

Could you share generated spec file for that tagged scenario?

> Do you have a reference where I can read about the tag option you are mentioning?

Sure. Please check out this release notes: https://playwright.dev/docs/release-notes#new-apis-2

**Comment by tjaeuth** [comment]
I think the original issue was updating playwright to 1.44.1 but nodejs was still using 1.41 during my tests.
Now after restarting everything it works like a charm.

I can even mix up tests generated by playwright-bdd and other playwright tests. Great work done here, thank you @vitalets

**Comment by vitalets** [comment]
You are welcome!
