### ISSUE TITLE
How can I give two fixtures file instead of one in importTestFrom ?

### ISSUE THREAD

**Issue by QAPranav** [vitalets/playwright-bdd#180]
Can I give two fixtures in importTestFrom something I am try is like this but getting error, Type 'string[]' is not assignable to type 'string | ImportTestFrom | undefined'. I know its type error that importTestFrom is just accepting string not array.

const testFixture = ['tests/fixtures/pagefixtures.ts', 'api_test/fixtures/apifixture.ts'];

const testDir = defineBddConfig({
  importTestFrom: testFixture,
  paths: ['tests/features/***.feature', 'api_tests/features/***.feature'],
  require: ['tests/steps/***.steps.ts', 'api_tests/steps/***.steps.ts'],
});

**Comment by vitalets** [comment]
`importTestFrom` can't accept array, because we need to get only one `test` instance in generate files: `import { test } from '...'`.
There are several options to achieve that:
* if your `tests` and `api_tests` are separate, you can create two Playwright projects:
  ```ts
  export default defineConfig({
    projects: [
      {
        name: 'page-tests',
        testDir: defineBddConfig({
          outputDir: './features-gen/page-tests',
          importTestFrom: 'tests/fixtures/pagefixtures.ts',
          paths: ['tests/features/*.feature'],
          require: ['tests/steps/*.steps.ts'],
        }),
      },
      {
        name: 'api-tests',
        testDir: defineBddConfig({
          outputDir: './features-gen/api-tests',
          importTestFrom: 'api_test/fixtures/apifixture.ts',
          paths: ['api_tests/features/*.feature'],
          require: ['api_tests/steps/*.steps.ts'],
        }),
      },
  ```
* if your features use fixtures from both files, then you can use Playwright's [mergeTests](https://playwright.dev/docs/release-notes#merge-test-fixtures) utility to get single test:
   ```ts
   // allFixtures.ts 
   import { mergeTests } from '@playwright/test';
   import { test as pageTest } from 'tests/fixtures/pagefixtures.ts';
   import { test as apiTest } from 'api_test/fixtures/apifixture.ts';

   export const test = mergeTests(pageTest, apiTest);
   ```

* you can try playwright-bdd v7 (rc), it tries [automatically detect](https://vitalets.github.io/playwright-bdd/#/guides/migration-v7?id=omit-importtestfrom) which file to use in importTestFrom. But there is no super magic - if fixtures file is ambiguous, playwright-bdd will throw an error, so you may need to apply `mergeTests` anyway.

**Comment by QAPranav** [comment]
Thank you @vitalets for your help. you are doing amazing work
