### ISSUE TITLE
Question: How to Change Logging Output Format in “Show Info” Section for playwright-bdd 7.5.0?

### ISSUE THREAD

**Issue by dawid-peda** [vitalets/playwright-bdd#239]
Hi,

I’ve recently updated playwright-bdd from version 7.4.2 to 7.5.0, and I noticed a change in how logs are displayed in the “Show Info” section at the end of the file.

In version 7.4.2, logs were directly attached as text, making it easy to view them within the report. However, in version 7.5.0, the logs are now provided as a downloadable file, which adds an extra step to access the test run details.

Is there a way to revert this change and have the logs displayed directly in the “Show Info” section as text rather than as a downloadable file?

Any guidance or configuration options that would help achieve this would be much appreciated.

This is how it looks in latest version:
<img width="530" alt="image" src="https://github.com/user-attachments/assets/f9ff635b-b79f-4a36-a11e-b2cba7beaf3c">

I prefer plain text like in previous version "playwright-bdd": "^7.4.2"
<img width="578" alt="image" src="https://github.com/user-attachments/assets/d7fbf118-919a-4948-afe2-ea60822a95ea">

I use [cucumber-html-reporter](https://www.npmjs.com/package/cucumber-html-reporter)

I have noticed that in older version, 'mime_type' has value 'text/plain'
```
          {
            "keyword": "After",
            "hidden": true,
            "result": {
              "status": "passed",
              "duration": 283000000
            },
            "embeddings": [
              {
                "data": "some data",
                "mime_type": "text/plain"
              }
            ]
          }
```

but in latest 7.5.0 version,  'mime_type' has value text/x.cucumber.log+plain
```
          {
            "keyword": "After",
            "hidden": true,
            "result": {
              "status": "passed",
              "duration": 2000000
            },
            "embeddings": [
              {
                "data": "some data",
                "mime_type": "application/zip"
              },
              {
                "data": "some data",
                "mime_type": "text/x.cucumber.log+plain"
              }
            ]
          }
```

Thank you in advance!

**Comment by vitalets** [comment]
The root cause is that cucumber-html-reporter does not handle `text/x.cucumber.log+plain` properly: https://github.com/gkushang/cucumber-html-reporter/issues/236

I've checked why mime type was changed in playwright-bdd v7.5:
New Cucumber native html reporter added pretty formatting for `text/x.cucumber.log+plain` compared to `text/plain`:

`text/x.cucumber.log+plain`:
![image](https://github.com/user-attachments/assets/bc0f05ab-5281-4fdc-b1f0-8d35215b7f0d)


`text/plain`:
![image](https://github.com/user-attachments/assets/83818fb6-cbf8-4b9b-8634-33d690e1b617)

As a workaround, you can add logs as attachment via `$testInfo`:
```ts
Given("I am on Playwright home page", async ({ page, $testInfo }) => {
  await $testInfo.attach("stdio", { body: "hello world" }); // <- adds hello world as `text/plain`
});
```
It can be wrapped as a helper `log` fixture. The only downside is that it's asynchronous, so we need to call it with `await` compared to `console.log`.

**Note**: cucumber-html-reporter looks [unmaintained](https://github.com/gkushang/cucumber-html-reporter/issues/296), maybe consider other alternatives, for example allure report?

**Comment by dawid-peda** [comment]
Vitaliy, thank you very much for your reply. I understand, maybe it's a good time to move to another reporter.
