### ISSUE TITLE
Feature: Scenario outline with examples in the title

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#67]
**The problem**
Hello @vitalets, I was trying to set up an example within the scenario title, but unfortunately it is not working.

Example:
```
Scenario Outline:  A <some> step is <result>
   When ....
   Then .....
Examples:
   | some    | result     |
   | passing | passed  |
   | failing   | skipped |

```

Is this possible to be implemented, or maybe I am doing something wrong?

**Comment by vitalets** [comment]
Hi @NikkTod !
What is expected output for your example?

Is it something like this:
```ts
test.describe(`A <some> step is <result>`, () => {

    test(`A passing step is passed`, ...);
    test(`A failing step is skipped `, ...);

});
```

Currently we have an [special comment syntax](https://vitalets.github.io/playwright-bdd/#/writing-features?id=customize-examples-title) to customize test titles for examples. E.g.:
```gherkin
Scenario Outline:  A <some> step is <result>
   When ....
   Then .....

# title-format: A <some> step is <result>
Examples:
   | some    | result     |
   | passing | passed  |
   | failing   | skipped |
```


But looking at your code I've realized that we can also use scenario title as a test title template. In simple cases it's more straightforward than special comments.

**Comment by NikkTod** [comment]
@vitalets thanks, the [special comment syntax](https://vitalets.github.io/playwright-bdd/#/writing-features?id=customize-examples-title) helps me have it. The # makes it a bit like a comment, but it did the trick :)

**Comment by vitalets** [comment]
Released in v5.6.0. Now scenario outline title will serve as a template for examples.
  Please re-check on your side and report if there are any issues.

**Comment by alescinskis** [comment]
Hi!
is it possible to disable/skip original scenario outline title in the report?
before update, `5.5.0`:
<img width="989" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/29544469/b7908ab1-e854-4eb5-b9ba-f4657067df0b">
after update, `5.6.0`:
<img width="984" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/29544469/99579466-4238-4d54-88a3-46b267339521">
I'd like to get rid of `Win Result: different sides, side <side>`

**Comment by vitalets** [comment]
@alescinskis so the expected report is the following?
```
TopCard: Win Result -> Win Result: different sides, side 1
TopCard: Win Result -> Win Result: different sides, side 2
TopCard: Win Result -> Win Result: different sides, side 3
```

Technically scenario outline is a separate `describe` block, that's why we have this title in the Playwright HTML report.
It was done to avoid duplicate test titles like `Example #x` and also to apply tags to Scenario outline itself.

We can add some logic or flag to skip generation of this extra `describe` block for cases when user defined Scenario outline template assuming it ensures test title uniqueness. But I think this adds extra complexity to the whole test generation process and can lead to bugs in the future.

My suggestion is to follow another direction. Currently I'm working on the next big feature in playwright-bdd - support of Cucumber reporter that is designed to display BDD reports. For example: https://github.com/vitalets/playwright-bdd/issues/67#issuecomment-1795361618 There we will have just scenario outline title and examples as a table - that is native way of displaying examples. And there is no need to struggle with examples test title.

**Comment by NikkTod** [comment]
Hi @vitalets, as you probably already saw, playwright new version now supports tags :) 

[New syntax](https://playwright.dev/docs/test-annotations#tag-tests) for adding tags to the tests (@-tokens in the test title are still supported):
test('test customer login', {
  tag: ['@fast', '@login'],
}, async ({ page }) => {
  // ...
});
Use --grep command line option to run only tests with certain tags.

npx playwright test --grep @fast

**Comment by vitalets** [comment]
@NikkTod Yes, that's good news! Created a separate issue for tracking that https://github.com/vitalets/playwright-bdd/issues/98

**Comment by vitalets** [comment]
Wrapping it into #122
