### ISSUE TITLE
Question:Do steps have to be Async? 

### ISSUE THREAD

**Issue by RichardCariven** [vitalets/playwright-bdd#97]
I am getting linting errors on the below step 

Then("the pathname should be {string}", async ({ page }, pathname) => {
  const url = new URL(page.url());
  expect(url.pathname).toBe(pathname);
  
  ESLint: Async arrow function has no 'await' expression.(@typescript-eslint/require-await)
  
  Is it a requirement for the steps to be Async or would we expect 
  
  Then("the pathname should be {string}",  ({ page }, pathname) => {
  const url = new URL(page.url());
  expect(url.pathname).toBe(pathname);
  
To work in all cases? My current test is passing with but that I am new to Typescript so have been copying out the steps as per all the examples I have found and haven't seen one that isn't async, not sure if there is a reason for that.

**Comment by vitalets** [comment]
Hi @RichardCariven !
Steps are not required to be async, your second example is correct:
```js
Then("the pathname should be {string}", ({ page }, pathname) => {
  const url = new URL(page.url());
  expect(url.pathname).toBe(pathname);
});
```

Although steps are usually async, because most of Playwright methods are async. For example, if you want to check page title instead of url, you need to use async step:
```js
Then("the title should be {string}", async ({ page }, expectedTitle) => {
  const title = await page.title(); // page.title() is async
  expect(title).toBe(expectedTitle);
});
```
Anyway, I will add this note to documentation to avoid such confusion 👍

**Comment by RichardCariven** [comment]
great thankyou
